#!/bin/bash

tests_begun=0
is_panicing=0
ret=0

fail(){ echo -e "\x1b[1;31m"TEST FAILED"\x1b[0m"
}

while true; do
	if (( ! tests_begun )); then
		read -r line || exit
		if [[ "$line" == *begin\ tests* ]]; then
			tests_begun=1
			continue
		fi
	fi

	if (( tests_begun )); then
		read -r line1 || exit 1
		if [ "$line1" = "end tests" ]; then break; fi
		read -r line2 || exit 1

		prefix=$(printf "%s\n" "$line2" | od -An -N1 -b)
		if [ "$prefix" = " 002" ]; then
			if [ "$line1" != "${line2:1}" ]; then
				(
					fail
					echo expected=
					echo "${line2:1}"
					echo "${line2:1}" | hexdump -C
					echo
					echo got=
					echo "$line1"
					echo "$line1" | hexdump -C
				) >&2

				exit 1
			fi
		fi

		if (( is_panicing )); then
			echo "$line1"
			echo "$line2"
		fi
		if [[ "$line1" = panic\!* ]]; then
			fail
			echo "$line2"
			is_panicing=1
			ret=1
		fi
	fi
done
exit $ret
